global.bot = "graal.era.free"
global.senha = "34615194"
global.prefix = "."
global.nome_sessao = "kzm"
global.aceitar_msg = "olá, seja bem vindo a minha inteligência artificial, comece digitando .acessar 😁"